In [9]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

data = pd.read_csv("anime.csv")
print(data.head(10))

                              Title      Production Episodes       Source  \
0                Shingeki no Kyojin      Wit Studio       25        Manga
1  Fullmetal Alchemist: Brotherhood           Bones       64        Manga
2                  Sword Art Online    A-1 Pictures       25  Light novel
3                     One Punch Man        Madhouse       12    Web manga
4             Boku no Hero Academia           Bones       13        Manga
5                       Tokyo Ghoul  Studio Pierrot       12        Manga
6                            Naruto  Studio Pierrot      220        Manga
7            Hunter x Hunter (2011)        Madhouse      148        Manga
8                  Kimetsu no Yaiba        ufotable       26        Manga
9       Shingeki no Kyojin Season 2      Wit Studio       12        Manga

                                      Genre                   Airdate  Rating  \
0              Action,Drama,Fantasy,Mystery  Apr 7, 2013, 01:58 (JST)    8.52
1     Action,Adventure,Comedy,Drama,Fantasy  Apr 5, 2009, 17:00 (JST)    9.16
2          Action,Adventure,Fantasy,Romance  Jul 8, 2012, 00:00 (JST)    7.20
3         Action,Comedy,Sci-Fi,Supernatural  Oct 5, 2015, 01:05 (JST)    8.52
4                             Action,Comedy  Apr 3, 2016, 17:00 (JST)    7.98
5  Action,Drama,Horror,Mystery,Supernatural  Jul 4, 2014, 00:00 (JST)    7.80
6                   Action,Adventure,Comedy  Oct 3, 2002, 19:30 (JST)    7.95
7                  Action,Adventure,Fantasy  Oct 2, 2011, 10:55 (JST)    9.06
8                       Action,Supernatural  Apr 6, 2019, 23:30 (JST)    8.57
9              Action,Drama,Fantasy,Mystery  Apr 1, 2017, 22:00 (JST)    8.49

      Voters                     Theme
0  3,142,121      Military,Super Power
1  2,676,911                  Military
2  2,586,628                      Game
3  2,583,068        Parody,Super Power
4  2,426,309        School,Super Power
5  2,315,361             Psychological
6  2,289,448  Martial Arts,Super Power
7  2,152,116               Super Power
8  2,112,029         Demons,Historical
9  2,086,165      Military,Super Power

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1992 entries, 0 to 1991
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       1992 non-null   object
 1   Production  1992 non-null   object
 2   Episodes    1992 non-null   object
 3   Source      1992 non-null   object
 4   Genre       1992 non-null   object
 5   Airdate     1020 non-null   object
 6   Rating      1944 non-null   float64
 7   Voters      1992 non-null   object
 8   Theme       1992 non-null   object
dtypes: float64(1), object(8)
memory usage: 140.2+ KB

In [17]:
data.Title = data.Title.str.lower()
data.Title = data.Title.str.replace(' ', '_')
data.Title = data.Title.str.replace(',', ' ')
data

,Title,Production,Episodes,Source,Genre,Airdate,Rating,Voters,Theme,episodes
0,shingeki_no_kyojin,Wit Studio,25,Manga,action_drama_fantasy_mystery,"Apr 7, 2013, 01:58 (JST)",8.52,"3,142,121","Military,Super Power",25
1,fullmetal_alchemist:_brotherhood,Bones,64,Manga,action_adventure_comedy_drama_fantasy,"Apr 5, 2009, 17:00 (JST)",9.16,"2,676,911",Military,64
2,sword_art_online,A-1 Pictures,25,Light novel,action_adventure_fantasy_romance,"Jul 8, 2012, 00:00 (JST)",7.20,"2,586,628",Game,25
3,one_punch_man,Madhouse,12,Web manga,action_comedy_sci-fi_supernatural,"Oct 5, 2015, 01:05 (JST)",8.52,"2,583,068","Parody,Super Power",12
4,boku_no_hero_academia,Bones,13,Manga,action_comedy,"Apr 3, 2016, 17:00 (JST)",7.98,"2,426,309","School,Super Power",13
...,...,...,...,...,...,...,...,...,...,...
1987,dog_days'_specials,Seven Arcs,13,-,action_adventure_fantasy,NaN,6.66,"8,687",-,13
1988,bleach:_gotei_13_omake,-,1,Manga,action_adventure,NaN,6.49,"8,682",-,1
1989,brain_powerd,Sunrise,26,Original,action_adventure_sci-fi,"Apr 8, 1998",6.10,"8,678",Mecha,26
1990,mobile_suit_gundam:_iron-blooded_orphans_-_ur√∞...,Sunrise Beyond,?,Original,action_drama_sci-fi,NaN,NaN,"8,665","Mecha,Space",NaN
1991,burn_up_scramble,AIC Spirits,12,Original,action_comedy_drama_sci-fi_ecchi,"Jan 12, 2004",6.19,"8,662",Police,12

In [18]:
data.describe()

            Rating
count  1944.000000
mean      7.150849
std       0.709454
min       2.960000
25%       6.720000
50%       7.210000
75%       7.590000
max       9.160000